language: node_js
node_js:
  - "8"
  - "10"
cache:
  directories:
    - node_modules
    - "$HOME/.npm"
notifications:
  email: false
install:
  - npm install
script:
  - npm run lint
  - npm run coverage
  - npm run build
after_script: "cat ./coverage/lcov.info | npx coveralls"
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
