language: node_js
node_js:
  - 6
  - 8
  - 10
cache:
  directories:
    - node_modules
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run coverage
  - npm run build
#after_script:
#  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls' # sends the coverage report to coveralls
