language: node_js
node_js:
  - 6
  - 8
  - 10
cache:
  directories:
    - node_modules
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run lint
  - npm run coverage
  - npm run build
after_script:
  # send the coverage report to coveralls
  - 'cat coverage/lcov.info | npx coveralls'
