language: node_js
node_js:
  # - "6"
  - "8"
  - "10"
cache:
  directories:
    - node_modules
    - "$HOME/.npm"
notifications:
  email: false
install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run build
jobs:
  include:
    # send the coverage report to coveralls
    - stage: coverage
      script: 'npm -v; npm run coverage -- --coverageReporters=text-lcov | coveralls'
      node_js: "10"
