language: node_js
node_js:
  # - "6"
  - "8"
  - "10"
cache:
  directories:
    - node_modules
    - "$HOME/.npm"
notifications:
  email: false
before_install:
  # - mkdir coverage
  # - ls -la
  - npm i -g npm@5
install:
  - npm ci
script:
  - npm run lint
  - npm test
  - npm run build
# after_script:
#   # send the coverage report to coveralls
#   - ls -la
#   - ls -la coverage
#   - 'cat coverage/lcov.info | npx coveralls'
jobs:
  include:
    # send the coverage report to coveralls
    - stage: coverage
      script: 'npm -v; npm run coverage -- --coverageReporters=text-lcov | coveralls'
      node_js: "10"
